# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      docker:
        image: docker/compose:1.29.2
        ports:
          - 80:80

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y protobuf-compiler
        python -m pip install --upgrade pip
        pip install -e .[dev]
    - name: Lint with flake8
      run: |
        flake8 .

    - name: Run unit tests
      run: |
        pytest tests/test_world_observer.py --cov=rcst --cov-report=xml --cov-append
        pytest tests/test_goal_observer.py --cov=rcst --cov-report=xml --cov-append

    - name: Start Docker Compose services
      run: docker compose -f .docker/consai-grsim-compose.yml up -d

    - name: Wait for game.py to start
      timeout-minutes: 5
      run: |
        CHECK_INTERVAL=10

        until docker top consai 2>/dev/null | grep -q game.py
        do
          echo "Waiting for game.py to start..."
          sleep $CHECK_INTERVAL
        done

        echo "game.py started!"

    - name: Run scenario tests
      run: pytest tests/test_scenario_*.py --vision_port=10020 --cov=rcst --cov-report=xml --cov-append

    - name: Get and print logs
      if: always()
      run: docker compose -f .docker/consai-grsim-compose.yml logs

    - name: Clean up Docker Compose services
      if: always()
      run: docker compose -f .docker/consai-grsim-compose.yml down

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
